### ISSUE TITLE
Create, edit, and view profile page

### ISSUE THREAD

**Issue by bdeleonardis1** [codebase-berkeley-mentored-project-sp18/CodeDoor#1]
localhost:8000/codedoor/createprofile should link to the create profile page
localhost:8000/codedoor/viewprofile/1 - view info about a specific profile
localhost:8000/codedoor/editprofile/1 - edit the info about a profile

You can make different templates for each of these pages, but if you can figure out how to combine view and edit that would be really cool (if you can’t don’t worry)

Profile should fill out all the fields that we talked about except username and password - Django gives us a lot of help with this and we’ll go over it next week

**Comment by theandrewchan** [comment]
Finished and merged. See the code review at #7
