### ISSUE TITLE
Group 1 / Slack Login and S3

### ISSUE THREAD

**Issue by bdeleonardis1** [codebase-berkeley-mentored-project-sp18/CodeDoor#15]
- Allow the user to login with their slack account. The first time they attempt to do this they should be brought to the create profile page. Official API https://api.slack.com/docs/sign-in-with-slack. Here is how to override the Username/Password authentication scheme in Django: https://docs.djangoproject.com/en/2.0/topics/auth/customizing/#authentication-backends, and here is a tutorial on that: https://micropyramid.com/blog/custom-password-less-authentication-in-django/.
- The basic idea is to obtain the authorization code by having the user login to slack, then use the authorization code to get the access token, use the access token to get their username, use the username to either log the user in or create an account for them (override the authentication with one that doesn't require a password).
- Create S3 buckets on AWS to hold images (company logo/profile pic)
- Actually display the image when they should be displayed
- Top right corner should display the user’s profile pic instead of just Andrew
- You’ll need to change the models to hold urls rather than imagefield/filefield
- The docs are pretty good: http://boto3.readthedocs.io/en/latest/guide/s3-example-creating-buckets.html. I'll set you up with an AWS account by the end of the day tomorrow. I want to make sure you can't run up my credit card!

**Comment by aidanjwang** [comment]
Also, we need to:
- Make it so user is logged out when she navigates to createprofile page
- Make it so user is logged in when she completes createprofile page
