### ISSUE TITLE
Group 3 / Application Improvements

### ISSUE THREAD

**Issue by bdeleonardis1** [codebase-berkeley-mentored-project-sp18/CodeDoor#17]
- Add .js form validation as well for the Application page
- Add a list of applications to the “Dashboard page” as well
- Link to creating an Application from the viewcompany page - company should be autofilled
- Link to creating an Application from the viewprofile page - look at the figma for how this should look
- Tabs for application 
- Paginate this as well
- See Group 2's issue for more details and helpful linls

**Comment by theandrewchan** [comment]
Also, application submissions are currently submitted under the profile with pk=1. They must be submitted under the pk of the currently logged in user. Basically right now, we are by default using company with pk=1 and profile with pk=1. These fields should all be autofilled with the correct `company` and `profile` objects.
