### ISSUE TITLE
Create, edit, and view company page

### ISSUE THREAD

**Issue by bdeleonardis1** [codebase-berkeley-mentored-project-sp18/CodeDoor#2]
/codedoor/createcompany  --> form to create company
/codedoor/viewcompany/1 --> view company with id 1
/codedoor/editcompany/1 --> edit form for a company
If you can merge view and edit together in some logical way (even if it is just a link from 1 to the other it’d be great)

**Comment by theandrewchan** [comment]
Finished and pull request merged, please see #4. 

@ekwkk, @indianwolverine, @commanderchewbacca, please review the code review in #4 as soon as you can.
