### ISSUE TITLE
Login Team

### ISSUE THREAD

**Issue by bdeleonardis1** [codebase-berkeley-mentored-project-sp18/CodeDoor#23]
- Slack login needs to actually work
- The first time you login with slack it should redirect you to a createprofile page where you can provide the additional information you need
- When you create a profile it should log you in too, I shouldn't need to log in again
- Make Andrew's beautiful face in the top right instead be the user's profile picture
- Make the face clickable so that it takes you to the profile pic

**Comment by theandrewchan** [comment]
Also the profile page should have the profile's email/linkedin/links and not Sophia's email/linkedin. 😛
