### ISSUE TITLE
Group 1 Work / Users and Logging in

### ISSUE THREAD

**Issue by bdeleonardis1** [codebase-berkeley-mentored-project-sp18/CodeDoor#8]
- Create login page, login view, logout view, logout screen.
- Link the Django built in User to the Profile you created
- Django user doesn’t have enough stuff for us, that’s why we made you create the profile
- Update your create profile page to be a create user page
- Don’t worry too much about the CSS for this page, we’ll be changing it again soon!
- Read this: (https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html) and implement option 2 (that’s the only section you have to read)
- codedoor/login
- codedoor/logout

**Comment by theandrewchan** [comment]
Finished and merged, see #11
